### PR TITLE
Introducing Build Profiles

### PR DESCRIPTION
**Pull request by tomalok**
This is a big update, directly related to issue #37 (build profiles), reorganizes `variables.yaml` into base, version, and arch core profiles, which are merged (and optionally tweaked) in build profiles.  Foundations are also laid to progress issues #28 (aarch64 AMIs), #22 (Setup CI), #20 (update generate/cleanup scripts), and #23 (retention policy).

Although there are still a couple of improvements I'm working on with regards to `setup-ami.sh` improvements, building AMIs from profiles is working...
```
make PROFILE=test  # all build targets of the test profile
make PROFILE=test BUILD=test-edge-x86_64 # just one build target
```
...and I'm hoping to get some feedback with what's been done so far.

### CODE REVIEW

**Comment by mcrute** [comment]
Thanks! At a glance this looks pretty good but I'll take a more detailed look before the end of the week.

**Comment by tomalok** [comment]
At the moment I'm not quite satisfied with YAML anchors/references for the profiles, specifically the way they merge shallowly (which is why there's all the extra references for `repos`, `pkgs`, and `svcs` -- and the great big `cat` of all the base profiles together to make sure we've got all potential anchors covered...

Considering switching to some other merge-on-demand mechanism, probably inside `resolve-profile.py`.

**Comment by tomalok** [comment]
Played around with using [HOCON](https://github.com/lightbend/config/blob/master/HOCON.md) configs instead over the weekend...  I'm liking it much better, and it's certainly much more DRY.  I'm going to switch `resolve-profile.py` over to use `pyhocon` and see how that goes.

**Comment by tomalok** [comment]
Building from HOCON profiles are working.

`pyhocon` includes a script to convert to json, yaml, properties, and canonical hocon...  may want to consider redoing the packer yaml config as hocon -- this would eliminate the need for the little `yaml2json.py` conversion script.

**Comment by tomalok** [comment]
I think this PR should be complete when the following is done...
- [ ] support `grub` bootloader (required for aarch64) 

...having these other pieces would also be nice, but are more related to other issues...
- [ ] harvest build `manifest.json` into releases
- [ ] build `README.md` (or other `.md` linked from there) from releases
- [ ] clean up old AMIs in AWS regions, based on EOL date (and perhaps only keep latest built release or revision)

**Comment by tomalok** [comment]
'grub-efi' bootloader detection/code-path is in the latest commit, but is as of yet untested -- will need to get an aarch64 profile build sorted out to test that.

successfully builds an edge-x86_64 AMI, though. oddly, though...
```
[    0.541285] random: crng done (trusting CPU's manufacturer)
```
... it appears that perhaps some new kernel config landed, or perhaps it's because I launched the test instance on a `t3a.nano` instead of a `t3.nano`?

**Comment by tomalok** [comment]
@mcrute - okay, i should be all done making tweaks and stuff for a little while...  ;)

**Comment by tomalok** [comment]
Updated the README, and addressed #48.

@mcrute - could you maybe expand a bit on what you originally had in mind with regards to the CloudFormation stuff, or is it time to drop that caveat?

**Comment by tomalok** [comment]
Dropping this PR for a new, more complete one.

**Pull request closed without merging**
